### ISSUE TITLE
Dropdown directive - event.path is not supported by firefox

### ISSUE THREAD

**Issue by SandraMarquardt** [maitrungduc1410/primeng-shadowdom-directives#1]
Thank you for your helpful package!!

I just wanted to point out that there is a console error when you use psdDropdown in firefox. 
![image](https://user-images.githubusercontent.com/73550467/136961253-ccdd412c-5eb0-41e0-b4ef-215297ee2f94.png)

This is linked to firefox inability to support event.path. As a work around, we've implemented a custom psdDropdown directive that uses event.composedPath. 

![image](https://user-images.githubusercontent.com/73550467/136961605-84122018-abf8-4a13-a79d-3860fadee20a.png)

Unless there's a good reason for you to use event.path, it might be helpful to update your package accordingly.

Thanks!

**Comment by maitrungduc1410** [comment]
sorry for late reply, I forgot to check your issue

I'll fix this soon

thanks for your feedback

**Comment by maitrungduc1410** [comment]
Hi @SandraMarquardt , this issue is fixed, please upgrade to version `0.0.5`
