### ISSUE TITLE
Input mask component not working

### ISSUE THREAD

**Issue by drekthral** [maitrungduc1410/primeng-shadowdom-directives#12]
It seems like we need a directive for p-inputMask component too.

When using the component in shadow dom I get this error:
![image](https://user-images.githubusercontent.com/14870273/229791382-4dc6fc1b-d534-4801-8ff1-7161538b534f.png)

Using the component outside shadow dom is without any problems.

**Comment by maitrungduc1410** [comment]
This library is intended to fix issue with overlay component only, I don't think InputMask gets affected by shadowDOM, can you give me example? (with code)

**Comment by maitrungduc1410** [comment]
Hi, please upgrade to `0.2.2`, new directive `psdInputMask` is added to solve the issue

**Comment by drekthral** [comment]
> Hi, please upgrade to `0.2.2`, new directive `psdInputMask` is added to solve the issue

Uh, sorry. I wanted to provide demo, but totally forgot about it. You are amazing ❤️
