### ISSUE TITLE
Has this been tested with Angular 16

### ISSUE THREAD

**Issue by zenith77** [maitrungduc1410/primeng-shadowdom-directives#13]
Hi there @maitrungduc1410 

I just did a quick test of upgrading the library to Angular 16. 99% of everything works, but the part that doesn't is the sub menus don't show when you click on a root menu item.

Is there a chance you could look into it?

**Comment by maitrungduc1410** [comment]
Sure, lemme check with Angular 16 and get back to you

Which primeng version are you using?

**Comment by maitrungduc1410** [comment]
hi @zenith77  which menu component are you referencing about?

**Comment by zenith77** [comment]
Hey there @maitrungduc1410 - appreciate the quick response. Apologies for the lack of detail! :)

The menu bars in question are; p-megamenu and p-menubar. The menu bars themselves show up, but the sub menus don't appear.

The version of primeng we are using is; 16.3.1

**Comment by maitrungduc1410** [comment]
hi @zenith77  pls upgrade to v1.0.1, I added support for Angular >= 16
