### ISSUE TITLE
Add a license

### ISSUE THREAD

**Issue by black-snow** [maitrungduc1410/primeng-shadowdom-directives#16]
Currently, I can't find any license information.

[npm](https://www.npmjs.com/package/primeng-shadowdom-directives) states MIT but the repo doesn't have a license file.

**Comment by maitrungduc1410** [comment]
Do you have any issue with licensing?

I created this repo is for open source, anyone can use for free, open for modification

**Comment by maitrungduc1410** [comment]
And it's not required for a repo to have LICENSE file, I think the one you're talking about npm is recommendation, and "should have" in some cases

**Comment by black-snow** [comment]
Thanks for the quick reply @maitrungduc1410 
Without a license it's ... unlicensed.

> You're under no obligation to choose a license. However, without a license, the default copyright laws apply, meaning that you retain all rights to your source code and no one may reproduce, distribute, or create derivative works from your work. If you're creating an open source project, we strongly encourage you to include an open source license. The [Open Source Guide](https://opensource.guide/legal/#which-open-source-license-is-appropriate-for-my-project) provides additional guidance on choosing the correct license for your project.

https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/licensing-a-repository

If you intend this to be free to use for pretty much anything MIT, Apache 2.0, 0BSD, the unlicense and a couple of others might be a good choice.

**Comment by black-snow** [comment]
Btw, I don't use this (just stumbled over it by accident), but thank you anyway for handing this to the public <3

**Comment by maitrungduc1410** [comment]
thanks for letting me know, it's really helpful :)

**Comment by black-snow** [comment]
You're welcome and thanks again for your FOSS contribution and quick replies ❤️
