### ISSUE TITLE
Support for paginator component

### ISSUE THREAD

**Issue by luboslav** [maitrungduc1410/primeng-shadowdom-directives#2]
Hi,
could you please add directive for PrimeNG paginator component? It uses dropdown for "rows-per-page" option.

![image](https://user-images.githubusercontent.com/7914658/173341892-251beffb-1ace-4989-8fae-a8321fe65839.png)

Thx.

**Comment by maitrungduc1410** [comment]
thanks for requesting, I'm working on it

**Comment by maitrungduc1410** [comment]
Hi @luboslav, please upgrade to `0.1.3`, Paginator is now supported

**Comment by luboslav** [comment]
Thanks.
