### ISSUE TITLE
Upgrade to Angular 13 and PrimeNG 13

### ISSUE THREAD

**Issue by antoniomolinadev** [maitrungduc1410/primeng-shadowdom-directives#3]
Hi! This package is essential for Microfrontend, and just I upgraded my project to Angular 13 and the latest version of PrimeNG 13 and I have problems about the compatibility of the package.

Is possible to upgrade it for works right?

T
![conflicting](https://user-images.githubusercontent.com/2808365/178509809-21c1d6b6-2b4e-4633-b87f-e71a93614dc7.PNG)
Y

**Comment by maitrungduc1410** [comment]
Hi @antoniomolinadev,
 
pls install version `0.1.5`, it should resolve the issue

**Comment by antoniomolinadev** [comment]
Now works fine, TY !! :)
