### ISSUE TITLE
Primeng virtual scroll styles not working inside litelement slot

### ISSUE THREAD

**Issue by nchaitra** [maitrungduc1410/primeng-shadowdom-directives#7]
We are using litelement library to create components. In angular application when we add primeng virtual scroll table inside litelement component nothing is getting loaded but when we use p-table without virtual scroll enabled it's working. 

Is there any limitation from primeng virtual scroll when used inside litelement

**Comment by maitrungduc1410** [comment]
What issue is it? can you lemme know?

**Comment by maitrungduc1410** [comment]
My library is to fix issue with "overlay" component inside ShadowDOM only, prime table is not such component, so it should work.

I did a test following example on [PrimeNG website](https://www.primefaces.org/primeng/table/virtualscroll) and it works fine:
<img width="1792" alt="Screenshot 2022-10-27 at 9 01 32 AM" src="https://user-images.githubusercontent.com/16630193/198173711-1f25f266-e419-4240-9cb7-6d04d9ee2bd1.png">
