### ISSUE TITLE
Question:  Why were some directives removed recently?

### ISSUE THREAD

**Issue by pdemro** [maitrungduc1410/primeng-shadowdom-directives#8]
Our team noticed that you've removed psdTooltip among other shadowdom fixes for this project.

Were they fixed at some point with PrimNG?  Our team is finding, at least with 13, the tooltip in particular still seems to have issues with the shadowdom.

Thanks for your input!

**Comment by maitrungduc1410** [comment]
HI @pdemro , thanks for pointing out.

as in my updated README:
```
Tooltip (*No directive required*)
```
That means, once you import this library, it just works
